<a href="https://colab.research.google.com/github/ankurkaiser/Classificatio-problem-using-Mall-Customers-dataset/blob/master/CollegeAdmission.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [4]:
from google.colab import files
uploaded = files.upload()

Saving College_admission.csv to College_admission.csv


In [26]:
college = pd.read_csv("College_admission.csv")

# New Section

In [27]:
college.isna()

admit    gre    gpa    ses  Gender_Male   Race   rank
0    False  False  False  False        False  False  False
1    False  False  False  False        False  False  False
2    False  False  False  False        False  False  False
3    False  False  False  False        False  False  False
4    False  False  False  False        False  False  False
..     ...    ...    ...    ...          ...    ...    ...
395  False  False  False  False        False  False  False
396  False  False  False  False        False  False  False
397  False  False  False  False        False  False  False
398  False  False  False  False        False  False  False
399  False  False  False  False        False  False  False

[400 rows x 7 columns]

In [8]:
college.shape

(400, 7)

In [9]:
college.describe

<bound method NDFrame.describe of      admit  gre   gpa  ses  Gender_Male  Race  rank
0        0  380  3.61    1            0     3     3
1        1  660  3.67    2            0     2     3
2        1  800  4.00    2            0     2     1
3        1  640  3.19    1            1     2     4
4        0  520  2.93    3            1     2     4
..     ...  ...   ...  ...          ...   ...   ...
395      0  620  4.00    2            0     2     2
396      0  560  3.04    2            0     1     3
397      0  460  2.63    3            0     2     2
398      0  700  3.65    1            1     1     2
399      0  600  3.89    2            1     3     3

[400 rows x 7 columns]>

In [24]:
college

array([['1.0', '0.0', '380.0', ..., '0.0', '3.0', '3.0'],
       ['0.0', '1.0', '660.0', ..., '0.0', '2.0', '3.0'],
       ['0.0', '1.0', '800.0', ..., '0.0', '2.0', '1.0'],
       ...,
       ['1.0', '0.0', '460.0', ..., '0.0', '2.0', '2.0'],
       ['1.0', '0.0', '700.0', ..., '1.0', '1.0', '2.0'],
       ['1.0', '0.0', '600.0', ..., '1.0', '3.0', '3.0']], dtype='<U32')

In [31]:
college['gre']=college['gre'].astype(int)

In [32]:
college['gpa']=college['gpa'].astype(int)

In [33]:
college.describe()

admit         gre         gpa  ...  Gender_Male        Race       rank
count  400.000000  400.000000  400.000000  ...      400.000  400.000000  400.00000
mean     0.317500  587.700000    2.902500  ...        0.475    1.962500    2.48500
std      0.466087  115.516536    0.478085  ...        0.500    0.823279    0.94446
min      0.000000  220.000000    2.000000  ...        0.000    1.000000    1.00000
25%      0.000000  520.000000    3.000000  ...        0.000    1.000000    2.00000
50%      0.000000  580.000000    3.000000  ...        0.000    2.000000    2.00000
75%      1.000000  660.000000    3.000000  ...        1.000    3.000000    3.00000
max      1.000000  800.000000    4.000000  ...        1.000    3.000000    4.00000

[8 rows x 7 columns]

In [40]:
from sklearn.preprocessing import StandardScaler

scaling = StandardScaler()

scaled=scaling.fit_transform(college)

In [41]:
college.head()

admit  gre  gpa  ses  Gender_Male  Race  rank
0      0  380    3    1            0     3     3
1      1  660    3    2            0     2     3
2      1  800    4    2            0     2     1
3      1  640    3    1            1     2     4
4      0  520    2    3            1     2     4

In [42]:
scaled.mean()

1.7129155237073843e-17

In [43]:
college['gre'].mean()

587.7

In [44]:
from sklearn.model_selection import train_test_split

X= college[['gre','gpa','Race','rank','ses']]
y= college[['admit']]

In [45]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,random_state=101)

In [46]:
from sklearn.linear_model import LogisticRegression

In [47]:
classify =LogisticRegression()

classify.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [49]:
predictions = classify.predict(X_test)

In [50]:
predictions

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [51]:
from sklearn.metrics import classification_report

In [53]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.69      0.94      0.80        81
           1       0.50      0.13      0.20        39

    accuracy                           0.68       120
   macro avg       0.60      0.53      0.50       120
weighted avg       0.63      0.68      0.60       120



In [55]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=4)
kmeans.fit(college)
kmeans.cluster_centers_

array([[3.71428571e-01, 6.47714286e+02, 2.98571429e+00, 2.00000000e+00,
        4.85714286e-01, 1.97142857e+00, 2.38571429e+00],
       [2.76595745e-01, 5.35460993e+02, 2.83687943e+00, 1.95035461e+00,
        4.82269504e-01, 1.85815603e+00, 2.54609929e+00],
       [4.56140351e-01, 7.67719298e+02, 3.10526316e+00, 1.96491228e+00,
        4.38596491e-01, 1.89473684e+00, 2.40350877e+00],
       [1.61290323e-01, 4.05483871e+02, 2.67741935e+00, 2.09677419e+00,
        4.67741935e-01, 2.24193548e+00, 2.64516129e+00]])

In [56]:
kmeans.labels_

array([3, 0, 2, 0, 1, 2, 1, 3, 1, 0, 2, 3, 2, 0, 0, 1, 2, 3, 2, 1, 1, 0,
       0, 0, 2, 2, 0, 1, 2, 1, 1, 2, 0, 2, 3, 3, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 3, 1, 1, 3, 3, 0, 3, 2, 0, 0, 2, 1, 3, 3, 0, 0, 1, 0, 0, 1, 0,
       2, 0, 1, 2, 0, 3, 1, 1, 2, 2, 1, 2, 1, 0, 0, 0, 1, 3, 1, 1, 0, 0,
       0, 0, 0, 2, 2, 1, 0, 0, 0, 1, 0, 3, 3, 1, 3, 1, 0, 2, 0, 1, 3, 1,
       0, 3, 3, 0, 2, 0, 3, 0, 2, 3, 1, 1, 1, 1, 2, 1, 0, 2, 1, 3, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 3, 1, 1, 1, 2, 2, 3, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 3, 2, 1, 0, 3, 1, 0, 2, 1, 0,
       1, 0, 0, 3, 0, 1, 0, 1, 1, 2, 1, 1, 1, 1, 0, 2, 0, 3, 0, 1, 0, 3,
       0, 1, 2, 1, 0, 3, 0, 2, 2, 0, 1, 1, 2, 1, 3, 0, 0, 0, 3, 3, 3, 1,
       1, 0, 1, 2, 2, 2, 0, 1, 1, 2, 1, 0, 3, 3, 2, 0, 0, 1, 1, 0, 3, 1,
       0, 0, 1, 2, 0, 3, 0, 0, 0, 0, 1, 1, 2, 0, 1, 0, 1, 0, 0, 3, 1, 0,
       1, 3, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 3, 1, 0, 0, 0, 3, 0, 1, 3, 0,
       2, 0, 2, 3, 0, 2, 0, 2, 1, 1, 1, 3, 1, 2, 0,

In [59]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predictions)

array([[76,  5],
       [34,  5]])