<a href="https://colab.research.google.com/github/ankurkaiser/Classificatio-problem-using-Mall-Customers-dataset/blob/master/first_tensorflow_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf


In [ ]:
zero_tensor = tf.zeros([3,3])

In [ ]:
print(zero_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [ ]:
ones_tensor = tf.ones([1,1])

In [ ]:
print(ones_tensor)

tf.Tensor([[1.]], shape=(1, 1), dtype=float32)


In [ ]:
fill_tensor = tf.fill([4,4], 16)
print(fill_tensor)

tf.Tensor(
[[16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]], shape=(4, 4), dtype=int32)


In [ ]:
first_constant =tf.constant([[1,2,3], [3,4,5]])
print(first_constant)

tf.Tensor(
[[1 2 3]
 [3 4 5]], shape=(2, 3), dtype=int32)


In [ ]:
mess_constant = tf.constant(['Kaiser'])
print(mess_constant)

tf.Tensor([b'Kaiser'], shape=(1,), dtype=string)


In [ ]:
lins_tensor = tf.linspace(0.,9.,6)
print(lins_tensor)

tf.Tensor([0.        1.8       3.6       5.3999996 7.2       9.       ], shape=(6,), dtype=float32)


In [ ]:
range_tensor =tf.range(3.,6.,0.5)
print(range_tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5], shape=(6,), dtype=float32)


In [ ]:
mat= tf.constant([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])

slic = tf.slice(mat,[1,1],[2,2])
print(slic)

tf.Tensor(
[[5. 6.]
 [8. 9.]], shape=(2, 2), dtype=float32)


In [ ]:
mat= tf.constant([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
rev=tf.reverse(mat,[0])
print(rev)

tf.Tensor(
[[7. 8. 9.]
 [4. 5. 6.]
 [1. 2. 3.]], shape=(3, 3), dtype=float32)


In [ ]:
x = tf.constant([1.,2.,3.])
y= tf.constant([6.,7.,8.])

sum = tf.add(x,y)
print(sum)

mul = tf.multiply(x,y)
print(mul)

div = tf.divide(x,y)
print(div)

div2 = x/y
print(div2)

rep =tf.sign(x)
print(rep)

tf.Tensor([ 7.  9. 11.], shape=(3,), dtype=float32)
tf.Tensor([ 6. 14. 24.], shape=(3,), dtype=float32)
tf.Tensor([0.16666667 0.2857143  0.375     ], shape=(3,), dtype=float32)
tf.Tensor([0.16666667 0.2857143  0.375     ], shape=(3,), dtype=float32)
tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)


In [ ]:
sq = tf.square(x)
print(sq)



tf.Tensor([1. 4. 9.], shape=(3,), dtype=float32)


In [ ]:
sqt = tf.sqrt(x)
print(sqt)

rsqt = tf.pow(x,y)
print(rsqt)

tf.Tensor([1.        1.4142135 1.7320508], shape=(3,), dtype=float32)
tf.Tensor([1.000e+00 1.280e+02 6.561e+03], shape=(3,), dtype=float32)


In [ ]:
cel = tf.floor(div)
print(cel)

tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)


In [ ]:
expon = tf.exp(x)
print(expon)

tf.Tensor([ 2.7182817  7.389056  20.085537 ], shape=(3,), dtype=float32)


In [ ]:
dot = tf.tensordot(x,y,axes =0)
print(dot)

tf.Tensor(
[[ 6.  7.  8.]
 [12. 14. 16.]
 [18. 21. 24.]], shape=(3, 3), dtype=float32)


In [ ]:
x = tf.constant([1.,2.,3.])
y= tf.constant([6.,7.,8.])

In [ ]:
norm_mat = tf.norm(x,ord='euclidean', axis=None, keepdims=None, name=None)
print(norm_mat)

tf.Tensor(3.7416575, shape=(), dtype=float32)
